--- #YAML:1.0
name:                PayflowPro
version:             3101
abstract:            Pure Perl PayflowPro payment gateway interface
license:             perl
author:              
    - Vivek Khera <vivek@khera.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    LWP:                           0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
